services:
  db:
    container_name: postgres16
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    ports:
      - 5432:5432
    networks:
      - bsn
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8888:8080
    networks:
      - bsn
    environment:
      ADMINER_DEFAULT_SERVER: db
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:24.0.2
    depends_on:
      - keycloak-db
    ports:
      - 9090:8080
      - 9000:9000
    networks:
      - keycloak
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db/keycloak_db
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ['start-dev']
  keycloak-db:
    container_name: keycloak_db
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: keycloak_db
    networks:
      - keycloak
  keycloak-adminer:
    container_name: keycloak_adminer
    image: adminer:latest
    ports:
      - 9888:8080
    networks:
      - keycloak
    environment:
      ADMINER_DEFAULT_SERVER: keycloak-db

networks:
  bsn:
    driver: bridge
  keycloak:
    driver: bridge
