services:
  db:
    container_name: postgres16
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    ports:
      - 5432:5432
    networks:
      - private
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8888:8080
    networks:
      - private
  mail-dev:
    container_name: maildev
    image: maildev/maildev:latest
    ports:
      - 1080:1080
      - 1025:1025
networks:
  private:
    driver: bridge
