spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: postgresql
  security:
    user:
      name: user
      password: password
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/book-social-network
          
application:
  file:
    uploads:
      photos-output-path: ./uploads

logging:
  level:
    org.springframework.security: TRACE

server:
  port: 8088

junit:
  jupiter:
    execution.parallel.enabled: true